## ZIP Fuction

In [1]:
list1 = [1,2,3,4]
list2 = ['Java', 'Python', 'Cpp', 'Csharp']

result = zip(list1,list2)

In [3]:
print(list(result))

[(1, 'Java'), (2, 'Python'), (3, 'Cpp'), (4, 'Csharp')]


In [4]:
data = {'Name':['Tom','nick','krish','alyal','maya'],'Age':[20,25,30,35,15]}

In [11]:
import pandas as pd
dfEmp = pd.DataFrame(data)
print(dfEmp)

NameError: name 'data' is not defined

In [7]:
alyalseries = pd.Series(dfEmp['Age'])

In [8]:
alyalseries

0    20
1    25
2    30
3    35
4    15
Name: Age, dtype: int64

In [10]:
display(dfEmp)

Name  Age
0    Tom   20
1   nick   25
2  krish   30
3  alyal   35
4   maya   15

In [13]:
result = alyalseries.apply(lambda x : 21 if x ==35 else x)

In [14]:
result

0    20
1    25
2    30
3    21
4    15
Name: Age, dtype: int64

# Numpy Arrays

In [ ]:
# Array creation functions
#np.array(), np.zeros(),np.ones(),np.empty()

In [15]:
import numpy as np

In [17]:
# Create an array using np.array()
array1 = np.array([1,2,4])
print("np.array():\n",array1)

np.array():
 [1 2 4]


In [18]:
array2 = np.array([3,4,5])
array2

array([3, 4, 5])

In [19]:
array3 = np.zeros((3,3))

In [20]:
array3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
array4 = np.random.rand(3,4)

In [33]:
display(array4*10)

array([[0.52650495, 3.42338421, 1.8868968 , 9.20497202],
       [3.69798947, 3.49563074, 0.11109076, 0.23204989],
       [0.60735869, 0.73717479, 3.19722729, 4.92224203]])

In [37]:
array1 = np.array([2,3,5,6,73,2])

In [38]:
array2 = np.reshape(array1,(2,3))

In [39]:
array2

array([[ 2,  3,  5],
       [ 6, 73,  2]])

In [40]:
array3 = np.transpose(array2)

In [41]:
array3

array([[ 2,  6],
       [ 3, 73],
       [ 5,  2]])

# Array Input and Output Functions

In [42]:
# Create an array
array1 = np.array([[1,2,3],[2,3,4]])

In [43]:
# save the array to a text file
np.savetxt('data.txt', array1)

In [44]:
array2 = np.loadtxt('data.txt')

In [46]:
array1

array([[1, 2, 3],
       [2, 3, 4]])

In [47]:
array2

array([[1., 2., 3.],
       [2., 3., 4.]])

In [12]:
from sklearn import datasets

In [13]:
iris = datasets.load_iris()


In [14]:
iris_df=pd.DataFrame(iris.data)
iris_df['class']=iris.target

iris_df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']

In [15]:
iris_df

sepal_len  sepal_wid  petal_len  petal_wid  class
0          5.1        3.5        1.4        0.2      0
1          4.9        3.0        1.4        0.2      0
2          4.7        3.2        1.3        0.2      0
3          4.6        3.1        1.5        0.2      0
4          5.0        3.6        1.4        0.2      0
..         ...        ...        ...        ...    ...
145        6.7        3.0        5.2        2.3      2
146        6.3        2.5        5.0        1.9      2
147        6.5        3.0        5.2        2.0      2
148        6.2        3.4        5.4        2.3      2
149        5.9        3.0        5.1        1.8      2

[150 rows x 5 columns]

# SciPy Package:-
- Helps to perform mathematical operations for faster results.

2x + y = 5
 and 4y - 5x = 7
Solve this

In [55]:
a = np.array([[2,1], [-5,4]])
b = np.array([[5], [7]])

from scipy import linalg
x= linalg.solve(a, b)

In [56]:
x

array([[1.],
       [3.]])

In [57]:
# To check result is correct or not
a.dot(x)-b

array([[0.],
       [0.]])

##### Solve 
2x +y=5
x-3y = -2

In [62]:
a = np.array([[2,1],[1,-3]])
b= np.array([[5],[-2]])

x= linalg.solve(a, b)

In [63]:
x

array([[1.85714286],
       [1.28571429]])

In [64]:
# To check result is correct or not
a.dot(x)-b

array([[ 0.0000000e+00],
       [-4.4408921e-16]])

##### Solve
2x + 5y - 4z = 0
5x - 8y - 6z = 5
x + 2y - 3z = 9

In [65]:
a = np.array([[2,5,-4],[5,-8,-6],[5,2,-3]])
b = np.array([[0],[5],[9]])

ans= linalg.solve(a, b)

In [66]:
ans

array([[2.57635468],
       [0.00985222],
       [1.30049261]])

In [67]:
# To check result is correct or not
a.dot(ans)-b

array([[0.],
       [0.],
       [0.]])

# ML USING SKLEARN

In [5]:
from sklearn import tree

Bumpy = 1
Smooth = 0
Orange = 0
Apple = 1

feature = [[140, Bumpy], [130, Bumpy], [150, Smooth], [170, Smooth]]

lable = [Orange, Orange, Apple, Apple]

model = tree.DecisionTreeClassifier()
model = model.fit(feature, lable)

print((model.predict([[160, Smooth]])))

[1]


In [16]:
iris_df

sepal_len  sepal_wid  petal_len  petal_wid  class
0          5.1        3.5        1.4        0.2      0
1          4.9        3.0        1.4        0.2      0
2          4.7        3.2        1.3        0.2      0
3          4.6        3.1        1.5        0.2      0
4          5.0        3.6        1.4        0.2      0
..         ...        ...        ...        ...    ...
145        6.7        3.0        5.2        2.3      2
146        6.3        2.5        5.0        1.9      2
147        6.5        3.0        5.2        2.0      2
148        6.2        3.4        5.4        2.3      2
149        5.9        3.0        5.1        1.8      2

[150 rows x 5 columns]

In [25]:
iris_df['class'].values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
data = iris_df.values
X = data[:, 0:4]
Y = data[:, 4]

In [27]:
# Split the data to train and test dataset.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [29]:
model = tree.DecisionTreeClassifier()
model = model.fit(X_train, y_train)

In [30]:
# Predict from the test dataset
predictions = model.predict(X_test)
# Calculate the accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.9666666666666667

In [32]:
pred = model.predict([[6.7, 3.0, 5.2, 2.3]])

In [33]:
pred

array([2.])